// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/[hotel]" | "/[hotel]/nueva-averia" | "/[hotel]/pendientes" | "/[hotel]/preventivo" | "/[hotel]/preventivo/boradas-ducha" | "/[hotel]/preventivo/cambio-bombas" | "/[hotel]/preventivo/fumigacion" | "/[hotel]/preventivo/historial" | "/[hotel]/preventivo/limpieza-filtros" | "/[hotel]/preventivo/mantenimiento-externo/[taskType]" | "/[hotel]/preventivo/reparaciones/[equipmentType]" | "/[hotel]/preventivo/revision-semestral" | "/[hotel]/preventivo/tareas-mensuales" | "/[hotel]/resueltas" | "/[hotel]/revisiones" | "/administracion" | "/administracion/contactos" | "/administracion/guia-virtual" | "/administracion/guia-virtual/[id]" | "/administracion/stock" | "/mantenimiento" | "/nueva-averia" | "/pendientes" | "/pisos" | "/recepcion" | "/recepcion/caledonian" | "/recepcion/chi" | "/resueltas"
type AppRouteHandlerRoutes = "/api/Calendar" | "/api/analytics" | "/api/contactos" | "/api/contactos/[id]" | "/api/external-maintenance" | "/api/filter-cleaning" | "/api/filter-cleaning/last-date" | "/api/filter-cleaning/status" | "/api/fumigation" | "/api/fumigation/last-date" | "/api/fumigation/status" | "/api/guia-virtual" | "/api/guia-virtual/[id]" | "/api/guia-virtual/[id]/fotos" | "/api/guia-virtual/[id]/historial" | "/api/inventory" | "/api/inventory/[id]" | "/api/inventory/movement" | "/api/maintenance" | "/api/maintenance/[id]" | "/api/maintenance/pending" | "/api/maintenance/resolved" | "/api/maintenance/stats" | "/api/monthly-tasks" | "/api/monthly-tasks/status" | "/api/preventive-maintenance/upcoming" | "/api/pump-change" | "/api/pump-change/history" | "/api/pump-change/last-date" | "/api/pump-change/status" | "/api/repair-history" | "/api/semiannual-review" | "/api/semiannual-review/[id]" | "/api/shower-grout" | "/api/shower-grout/last-date"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/[hotel]": { "hotel": string; }
  "/[hotel]/nueva-averia": { "hotel": string; }
  "/[hotel]/pendientes": { "hotel": string; }
  "/[hotel]/preventivo": { "hotel": string; }
  "/[hotel]/preventivo/boradas-ducha": { "hotel": string; }
  "/[hotel]/preventivo/cambio-bombas": { "hotel": string; }
  "/[hotel]/preventivo/fumigacion": { "hotel": string; }
  "/[hotel]/preventivo/historial": { "hotel": string; }
  "/[hotel]/preventivo/limpieza-filtros": { "hotel": string; }
  "/[hotel]/preventivo/mantenimiento-externo/[taskType]": { "hotel": string; "taskType": string; }
  "/[hotel]/preventivo/reparaciones/[equipmentType]": { "hotel": string; "equipmentType": string; }
  "/[hotel]/preventivo/revision-semestral": { "hotel": string; }
  "/[hotel]/preventivo/tareas-mensuales": { "hotel": string; }
  "/[hotel]/resueltas": { "hotel": string; }
  "/[hotel]/revisiones": { "hotel": string; }
  "/administracion": {}
  "/administracion/contactos": {}
  "/administracion/guia-virtual": {}
  "/administracion/guia-virtual/[id]": { "id": string; }
  "/administracion/stock": {}
  "/api/analytics": {}
  "/api/Calendar": {}
  "/api/contactos": {}
  "/api/contactos/[id]": { "id": string; }
  "/api/external-maintenance": {}
  "/api/filter-cleaning": {}
  "/api/filter-cleaning/last-date": {}
  "/api/filter-cleaning/status": {}
  "/api/fumigation": {}
  "/api/fumigation/last-date": {}
  "/api/fumigation/status": {}
  "/api/guia-virtual": {}
  "/api/guia-virtual/[id]": { "id": string; }
  "/api/guia-virtual/[id]/fotos": { "id": string; }
  "/api/guia-virtual/[id]/historial": { "id": string; }
  "/api/inventory": {}
  "/api/inventory/[id]": { "id": string; }
  "/api/inventory/movement": {}
  "/api/maintenance": {}
  "/api/maintenance/[id]": { "id": string; }
  "/api/maintenance/pending": {}
  "/api/maintenance/resolved": {}
  "/api/maintenance/stats": {}
  "/api/monthly-tasks": {}
  "/api/monthly-tasks/status": {}
  "/api/preventive-maintenance/upcoming": {}
  "/api/pump-change": {}
  "/api/pump-change/history": {}
  "/api/pump-change/last-date": {}
  "/api/pump-change/status": {}
  "/api/repair-history": {}
  "/api/semiannual-review": {}
  "/api/semiannual-review/[id]": { "id": string; }
  "/api/shower-grout": {}
  "/api/shower-grout/last-date": {}
  "/mantenimiento": {}
  "/nueva-averia": {}
  "/pendientes": {}
  "/pisos": {}
  "/recepcion": {}
  "/recepcion/caledonian": {}
  "/recepcion/chi": {}
  "/resueltas": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
