// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/[hotel]/nueva-averia/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[hotel]/nueva-averia">> = Specific
  const handler = {} as typeof import("../../app/[hotel]/nueva-averia/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[hotel]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[hotel]">> = Specific
  const handler = {} as typeof import("../../app/[hotel]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[hotel]/pendientes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[hotel]/pendientes">> = Specific
  const handler = {} as typeof import("../../app/[hotel]/pendientes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[hotel]/preventivo/boradas-ducha/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[hotel]/preventivo/boradas-ducha">> = Specific
  const handler = {} as typeof import("../../app/[hotel]/preventivo/boradas-ducha/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[hotel]/preventivo/cambio-bombas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[hotel]/preventivo/cambio-bombas">> = Specific
  const handler = {} as typeof import("../../app/[hotel]/preventivo/cambio-bombas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[hotel]/preventivo/fumigacion/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[hotel]/preventivo/fumigacion">> = Specific
  const handler = {} as typeof import("../../app/[hotel]/preventivo/fumigacion/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[hotel]/preventivo/historial/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[hotel]/preventivo/historial">> = Specific
  const handler = {} as typeof import("../../app/[hotel]/preventivo/historial/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[hotel]/preventivo/limpieza-filtros/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[hotel]/preventivo/limpieza-filtros">> = Specific
  const handler = {} as typeof import("../../app/[hotel]/preventivo/limpieza-filtros/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[hotel]/preventivo/mantenimiento-externo/[taskType]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[hotel]/preventivo/mantenimiento-externo/[taskType]">> = Specific
  const handler = {} as typeof import("../../app/[hotel]/preventivo/mantenimiento-externo/[taskType]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[hotel]/preventivo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[hotel]/preventivo">> = Specific
  const handler = {} as typeof import("../../app/[hotel]/preventivo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[hotel]/preventivo/reparaciones/[equipmentType]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[hotel]/preventivo/reparaciones/[equipmentType]">> = Specific
  const handler = {} as typeof import("../../app/[hotel]/preventivo/reparaciones/[equipmentType]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[hotel]/preventivo/revision-semestral/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[hotel]/preventivo/revision-semestral">> = Specific
  const handler = {} as typeof import("../../app/[hotel]/preventivo/revision-semestral/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[hotel]/preventivo/tareas-mensuales/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[hotel]/preventivo/tareas-mensuales">> = Specific
  const handler = {} as typeof import("../../app/[hotel]/preventivo/tareas-mensuales/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[hotel]/resueltas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[hotel]/resueltas">> = Specific
  const handler = {} as typeof import("../../app/[hotel]/resueltas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[hotel]/revisiones/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[hotel]/revisiones">> = Specific
  const handler = {} as typeof import("../../app/[hotel]/revisiones/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/administracion/contactos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/administracion/contactos">> = Specific
  const handler = {} as typeof import("../../app/administracion/contactos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/administracion/guia-virtual/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/administracion/guia-virtual/[id]">> = Specific
  const handler = {} as typeof import("../../app/administracion/guia-virtual/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/administracion/guia-virtual/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/administracion/guia-virtual">> = Specific
  const handler = {} as typeof import("../../app/administracion/guia-virtual/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/administracion/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/administracion">> = Specific
  const handler = {} as typeof import("../../app/administracion/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/administracion/stock/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/administracion/stock">> = Specific
  const handler = {} as typeof import("../../app/administracion/stock/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/mantenimiento/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mantenimiento">> = Specific
  const handler = {} as typeof import("../../app/mantenimiento/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/nueva-averia/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/nueva-averia">> = Specific
  const handler = {} as typeof import("../../app/nueva-averia/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/pendientes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pendientes">> = Specific
  const handler = {} as typeof import("../../app/pendientes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/pisos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pisos">> = Specific
  const handler = {} as typeof import("../../app/pisos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/recepcion/caledonian/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recepcion/caledonian">> = Specific
  const handler = {} as typeof import("../../app/recepcion/caledonian/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/recepcion/chi/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recepcion/chi">> = Specific
  const handler = {} as typeof import("../../app/recepcion/chi/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/recepcion/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recepcion">> = Specific
  const handler = {} as typeof import("../../app/recepcion/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/resueltas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/resueltas">> = Specific
  const handler = {} as typeof import("../../app/resueltas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/Calendar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/Calendar">> = Specific
  const handler = {} as typeof import("../../app/api/Calendar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/analytics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/analytics">> = Specific
  const handler = {} as typeof import("../../app/api/analytics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/contactos/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contactos/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/contactos/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/contactos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contactos">> = Specific
  const handler = {} as typeof import("../../app/api/contactos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/external-maintenance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/external-maintenance">> = Specific
  const handler = {} as typeof import("../../app/api/external-maintenance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/filter-cleaning/last-date/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/filter-cleaning/last-date">> = Specific
  const handler = {} as typeof import("../../app/api/filter-cleaning/last-date/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/filter-cleaning/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/filter-cleaning">> = Specific
  const handler = {} as typeof import("../../app/api/filter-cleaning/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/filter-cleaning/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/filter-cleaning/status">> = Specific
  const handler = {} as typeof import("../../app/api/filter-cleaning/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/fumigation/last-date/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/fumigation/last-date">> = Specific
  const handler = {} as typeof import("../../app/api/fumigation/last-date/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/fumigation/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/fumigation">> = Specific
  const handler = {} as typeof import("../../app/api/fumigation/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/fumigation/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/fumigation/status">> = Specific
  const handler = {} as typeof import("../../app/api/fumigation/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/guia-virtual/[id]/fotos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guia-virtual/[id]/fotos">> = Specific
  const handler = {} as typeof import("../../app/api/guia-virtual/[id]/fotos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/guia-virtual/[id]/historial/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guia-virtual/[id]/historial">> = Specific
  const handler = {} as typeof import("../../app/api/guia-virtual/[id]/historial/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/guia-virtual/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guia-virtual/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/guia-virtual/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/guia-virtual/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guia-virtual">> = Specific
  const handler = {} as typeof import("../../app/api/guia-virtual/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/inventory/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inventory/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/inventory/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/inventory/movement/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inventory/movement">> = Specific
  const handler = {} as typeof import("../../app/api/inventory/movement/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/inventory/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inventory">> = Specific
  const handler = {} as typeof import("../../app/api/inventory/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/maintenance/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/maintenance/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/maintenance/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/maintenance/pending/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/maintenance/pending">> = Specific
  const handler = {} as typeof import("../../app/api/maintenance/pending/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/maintenance/resolved/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/maintenance/resolved">> = Specific
  const handler = {} as typeof import("../../app/api/maintenance/resolved/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/maintenance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/maintenance">> = Specific
  const handler = {} as typeof import("../../app/api/maintenance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/maintenance/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/maintenance/stats">> = Specific
  const handler = {} as typeof import("../../app/api/maintenance/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/monthly-tasks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/monthly-tasks">> = Specific
  const handler = {} as typeof import("../../app/api/monthly-tasks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/monthly-tasks/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/monthly-tasks/status">> = Specific
  const handler = {} as typeof import("../../app/api/monthly-tasks/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/preventive-maintenance/upcoming/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/preventive-maintenance/upcoming">> = Specific
  const handler = {} as typeof import("../../app/api/preventive-maintenance/upcoming/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/pump-change/history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pump-change/history">> = Specific
  const handler = {} as typeof import("../../app/api/pump-change/history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/pump-change/last-date/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pump-change/last-date">> = Specific
  const handler = {} as typeof import("../../app/api/pump-change/last-date/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/pump-change/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pump-change">> = Specific
  const handler = {} as typeof import("../../app/api/pump-change/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/pump-change/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pump-change/status">> = Specific
  const handler = {} as typeof import("../../app/api/pump-change/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/repair-history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/repair-history">> = Specific
  const handler = {} as typeof import("../../app/api/repair-history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/semiannual-review/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/semiannual-review/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/semiannual-review/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/semiannual-review/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/semiannual-review">> = Specific
  const handler = {} as typeof import("../../app/api/semiannual-review/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/shower-grout/last-date/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/shower-grout/last-date">> = Specific
  const handler = {} as typeof import("../../app/api/shower-grout/last-date/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/shower-grout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/shower-grout">> = Specific
  const handler = {} as typeof import("../../app/api/shower-grout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
